### ISSUE TITLE
a

### ISSUE THREAD

**Issue by dev6920** [seadhy/Guilded-Account-Creator#1]
account not created , retrying fix?

**Comment by dev6920** [comment]
![image](https://user-images.githubusercontent.com/117775515/202293649-4560eef3-b0fa-4938-804f-2c55ea5ac1fd.png)
![image](https://user-images.githubusercontent.com/117775515/202293710-29e7939d-af1c-4445-9a67-a6bef399af5e.png)

**Comment by seadhy** [comment]
please put proxies to data/proxies.txt file
