### ISSUE TITLE
b

### ISSUE THREAD

**Issue by xRolTe** [seadhy/Guilded-Account-Creator#2]
![image](https://user-images.githubusercontent.com/87205971/204638593-591c84b3-bda8-4ab8-aa9c-5ea860df4963.png)

<h1> Böyle bir hata alıyorum sebebi ve çözümünü öğrenebilirmiyim ? <h1/>

![image](https://user-images.githubusercontent.com/87205971/204639139-bd5b8d9d-763e-4994-ae18-72612d0ed704.png)

<h3> Ayarlarda bu şekilde  <h3/>

**Comment by seadhy** [comment]
Bu discord hesap oluşturucusu değil. Guilded hesap oluşturucusu. Bunu discord sanan 4. kişisin, hiçbirinizin aklına başlığa bakmak gelmiyor mu 🙉
