### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Minhe173** [seadhy/Guilded-Account-Creator#3]
![image](https://user-images.githubusercontent.com/88653001/209441305-073945a6-bd2b-429d-8426-786f59da5034.png)
![image](https://user-images.githubusercontent.com/88653001/209441311-25a8c9ee-f63c-433b-8315-a93290470d2d.png)
![image](https://user-images.githubusercontent.com/88653001/209441318-e96b956e-d25e-4b8a-98a6-97e360d93e2a.png)
@seadhy help please

**Comment by seadhy** [comment]
If you read the error, it already says where the error is.
![image](https://user-images.githubusercontent.com/82868382/209444847-fd0b2258-556a-4817-802f-6be9f5539773.png)
Line 5, hmm. 
![image](https://user-images.githubusercontent.com/82868382/209444870-feeb5a38-f9d7-4a36-b798-af2dd0915568.png)
Yes, the error is here. Change `"text` to `"text"`.
